// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKmV2cs2xKXfu4t4mmRJN8hu5Kjki-qHI',
    appId: '1:881658572042:web:af60fb89d4fa00aba79ef3',
    messagingSenderId: '881658572042',
    projectId: 'fluttercoursfirebase-8867b',
    authDomain: 'fluttercoursfirebase-8867b.firebaseapp.com',
    storageBucket: 'fluttercoursfirebase-8867b.firebasestorage.app',
    measurementId: 'G-B2PH986H88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc30fYqxqdVUbb-TWqXfdh52Nc_84P7TI',
    appId: '1:881658572042:android:49c17c933699504fa79ef3',
    messagingSenderId: '881658572042',
    projectId: 'fluttercoursfirebase-8867b',
    storageBucket: 'fluttercoursfirebase-8867b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpwbKYUTaDfef0nxw4Hakw3uBm8yZpWgE',
    appId: '1:881658572042:ios:ece8377b4affce52a79ef3',
    messagingSenderId: '881658572042',
    projectId: 'fluttercoursfirebase-8867b',
    storageBucket: 'fluttercoursfirebase-8867b.firebasestorage.app',
    iosBundleId: 'com.example.flutterAvanceFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpwbKYUTaDfef0nxw4Hakw3uBm8yZpWgE',
    appId: '1:881658572042:ios:ece8377b4affce52a79ef3',
    messagingSenderId: '881658572042',
    projectId: 'fluttercoursfirebase-8867b',
    storageBucket: 'fluttercoursfirebase-8867b.firebasestorage.app',
    iosBundleId: 'com.example.flutterAvanceFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKmV2cs2xKXfu4t4mmRJN8hu5Kjki-qHI',
    appId: '1:881658572042:web:cff418dc68cfa1f8a79ef3',
    messagingSenderId: '881658572042',
    projectId: 'fluttercoursfirebase-8867b',
    authDomain: 'fluttercoursfirebase-8867b.firebaseapp.com',
    storageBucket: 'fluttercoursfirebase-8867b.firebasestorage.app',
    measurementId: 'G-MM1MXVQZ3E',
  );
}
